[package]
authors = ["Sean Bowe <sean@z.cash>"]
description = "Cryptographic library for Zcash Sapling"
documentation = "https://github.com/zcash/sapling"
homepage = "https://github.com/zcash/sapling"
license = "MIT/Apache-2.0"
name = "sapling"
repository = "https://github.com/zcash/sapling"
version = "0.0.1"

[dependencies]
bellman = "0.0.5"

[dependencies.pairing]
version = "0.13"
features = ["u128-support"]
