[package]
authors = ["Sean Bowe <sean@z.cash>"]
description = "Cryptographic library for Zcash Sapling"
documentation = "https://github.com/zcash/sapling"
homepage = "https://github.com/zcash/sapling"
license = "MIT/Apache-2.0"
name = "sapling"
repository = "https://github.com/zcash/sapling"
version = "0.0.1"

[dependencies.pairing]
version = "~0.13.2"
features = ["expose-arith"]

[dependencies]
rand = "0.3"
blake2 = "0.7"
digest = "0.7"
bellman = "0.0.6"

[features]
default = ["u128-support"]
u128-support = ["pairing/u128-support"]
